name: 'Deploy to WordPress'

on:
  push:
    branches:
      - 'main'
      - 'master'

env:
  WP_USERNAME: ${{ vars.WP_USERNAME }} # Your WordPress username. Needs admin privileges.
  WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }} # Application password for user specified in WP_USERNAME
  WP_HOME: ${{ vars.WP_HOME }} # The value from home_url()
  BUNDLE_DIRECTORY: ${{ vars.BUNDLE_DIRECTORY }} # Path relative to project root of theme bundle (should have a directory inside it that contains all theme code)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: 'actions/checkout@v3'

      - name: 'Deploy WordPress Theme'
        run: |
            cd ${{ env.BUNDLE_DIRECTORY }}
            zip bundle.zip -r .
            curl --user "${{ env.WP_USERNAME }}:${{ env.WP_APP_PASSWORD }}" ${{ env.WP_HOME }}/__cicd__/deploy_theme -F "themezip=@bundle.zip" --max-time 900
